# Generated by Django 6.0.3 on 2026-05-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehiculo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
