# Generated by Django 6.0.3 on 2026-03-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_estadia_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadia',
            old_name='fecha_salida',
            new_name='fecha_salida_estimada',
        ),
        migrations.AddField(
            model_name='estadia',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estadia',
            name='fecha_salida_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estadia',
            name='tipo_estadia',
            field=models.CharField(choices=[('hora', 'Por hora'), ('dia', 'Por día'), ('mes', 'Por mes'), ('default', 'Seleccionar duración')], default='default', max_length=10),
        ),
    ]
