# Generated by Django 6.0.3 on 2026-03-17 20:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_rename_fecha_salida_estadia_fecha_salida_estimada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadia',
            name='fecha_ingreso',
        ),
        migrations.AddField(
            model_name='estadia',
            name='fecha_entrada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='tipo_estadia',
            field=models.CharField(choices=[('default', 'Seleccionar duración'), ('hora', 'Por hora'), ('dia', 'Por día'), ('mes', 'Por mes')], default='default', max_length=10),
        ),
    ]
