# Generated by Django 6.0.3 on 2026-03-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_remove_estadia_fecha_ingreso_estadia_fecha_entrada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadiaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_espacios', models.IntegerField()),
            ],
        ),
    ]
