# Generated by Django 6.0.3 on 2026-03-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_estadiaconfig'),
        ('vehicles', '0002_alter_vehiculo_patente'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='estadia',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('vehiculo',), name='unique_active_estadia_per_vehicle'),
        ),
    ]
