# Generated by Django 6.0.3 on 2026-06-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_estadia_unique_active_estadia_per_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_limite', models.DateField()),
                ('frase_secreta', models.CharField(default='MiGarageSecreto123', max_length=100)),
            ],
        ),
    ]
