# Generated by Django 4.2.11 on 2026-06-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_configlicencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configlicencia',
            name='frase_secreta',
            field=models.CharField(default='MIGARAGE123', max_length=100),
        ),
        migrations.AlterField(
            model_name='configlicencia',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='estadiaconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
