# Generated by Django 6.0.3 on 2026-07-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_alter_configlicencia_frase_secreta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configlicencia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='estadiaconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
