# Generated by Django 6.0.3 on 2026-07-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_alter_configlicencia_id_alter_estadia_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadia',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
