# Generated by Django 6.0.3 on 2026-07-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0010_estadia_notas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_dueno', models.CharField(default='1234', max_length=10)),
            ],
        ),
    ]
