# Generated by Django 6.0.3 on 2026-03-24 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_estadiaconfig'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estadia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='parking.estadia'),
        ),
    ]
