# Generated by Django 6.0.3 on 2026-04-01 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_pago_estadia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='pago_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversiones', to='payments.pago'),
        ),
        migrations.AddField(
            model_name='pago',
            name='tipo',
            field=models.CharField(choices=[('pago', 'Pago'), ('reverso', 'Reverso')], default='pago', max_length=10),
        ),
    ]
