# Generated by Django 4.2.11 on 2026-06-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_pago_pago_original_pago_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
